# Utilitários de Sistema para Environment Dev Script
# Este arquivo contém componentes relacionados a utilitários do sistema

# Definição movida para common_utils.yaml

# Definição movida para system_optimization_windows.yaml

# Definição movida para common_utils.yaml

Vulkan SDK:
  category: Runtimes
  description: SDK para desenvolvimento com a API gráfica Vulkan
  download_url: https://sdk.lunarg.com/sdk/download/1.3.261.1/windows/VulkanSDK-1.3.261.1-Installer.exe
  install_method: exe
  install_args: /S
  hash: HASH_PENDENTE_VERIFICACAO
  hash_algorithm: sha256
  extract_path: 'C:\VulkanSDK\1.3.261.1'
  verify_actions:
    - type: env_var_exists
      name: VULKAN_SDK
    - type: directory_exists
      path: '${env:VULKAN_SDK}\Bin' 